name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            experimental-features = nix-command flakes

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: cachix/cachix-action@v15
        if: ${{ env.CACHIX_AUTH_TOKEN != '' }}
        with:
          name: blxs-custom-blender
          authToken: ${{ env.CACHIX_AUTH_TOKEN }}

      - name: Build Blender
        run: nix build -L .#blxs-custom-blender
